DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS fridge;
DROP TABLE IF EXISTS item;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE fridge (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fridgeName TEXT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);

CREATE TABLE item (
  itemName TEXT NOT NULL,
  spoilDate TEXT NOT NULL,
  itemType TEXT NOT NULL,
  fridge INTEGER NOT NULL,
  FOREIGN KEY (fridge) REFERENCES fridge (id)
  PRIMARY KEY (itemName, spoilDate, itemType)
)